//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankaIsletmeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalisanProfil
    {
        public int CalisanID { get; set; }
        public string CalisanAdi { get; set; }
        public string CalisanSoyadi { get; set; }
        public string CalisanBirim { get; set; }
        public string CalisanSube { get; set; }
        public string CalisanUnvan { get; set; }
        public string CalisanKullaniciAdi { get; set; }
        public string CalisanSifre { get; set; }
    }
}
