//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankaIsletmeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriHesaplari
    {
        public int HesapID { get; set; }
        public string HesapNo { get; set; }
        public int MusteriID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public int ParaBirimiID { get; set; }
        public string ParaBirimiKodu { get; set; }
        public decimal HesapBakiyesi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual ParaBirimi ParaBirimi { get; set; }
    }
}
